version: '3'

x-build-backend: &build_backend_env
  build:
    context: .
    dockerfile: Dockerfile
    target: dev
  volumes:
    - .:/opt/fantasy_league
  env_file:
    - variables/web.env
  depends_on:
    - db
    - redis
    - minio

services:
  db:
    image: postgres:16.0
    container_name: fantasy-league-be-db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    env_file:
      - variables/db.env

  web:
    <<: *build_backend_env
    container_name: fantasy-league-be-web
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'

  redis:
    container_name: fantasy-league-be-redis
    image: 'redis:alpine'

  minio:
    image: quay.io/minio/minio
    container_name: fantasy-league-be-minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/minio/data:/data
    env_file:
      - variables/minio.env
    command: server /data --console-address ":9001"

  delayed_task_worker:
    <<: *build_backend_env
    container_name: fantasy-league-be-task-worker
    command: python manage.py run_huey
