--
-- PostgreSQL database dump
--

-- Dumped from database version 16.0 (Debian 16.0-1.pgdg120+1)
-- Dumped by pg_dump version 16.0 (Debian 16.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO fantasy_league;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO fantasy_league;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO fantasy_league;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO fantasy_league;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO fantasy_league;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO fantasy_league;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO fantasy_league;

--
-- Name: match_gameweek; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_gameweek (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    number smallint NOT NULL,
    actual_from timestamp with time zone NOT NULL,
    actual_to timestamp with time zone NOT NULL,
    CONSTRAINT match_gameweek_number_check CHECK ((number >= 0))
);


ALTER TABLE public.match_gameweek OWNER TO fantasy_league;

--
-- Name: match_lineup; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_lineup (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    in_start boolean NOT NULL,
    player_id uuid NOT NULL,
    match_id uuid NOT NULL
);


ALTER TABLE public.match_lineup OWNER TO fantasy_league;

--
-- Name: match_match; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_match (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    home_club_goals smallint,
    away_club_goals smallint,
    start_time timestamp with time zone NOT NULL,
    full_time boolean NOT NULL,
    away_club_id character varying(255) NOT NULL,
    gameweek_id uuid NOT NULL,
    home_club_id character varying(255) NOT NULL,
    CONSTRAINT match_match_away_club_goals_check CHECK ((away_club_goals >= 0)),
    CONSTRAINT match_match_home_club_goals_check CHECK ((home_club_goals >= 0))
);


ALTER TABLE public.match_match OWNER TO fantasy_league;

--
-- Name: match_matchaction; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_matchaction (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    code character varying NOT NULL,
    name character varying(100) NOT NULL,
    for_display boolean NOT NULL
);


ALTER TABLE public.match_matchaction OWNER TO fantasy_league;

--
-- Name: match_matchevent; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_matchevent (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    minute smallint NOT NULL,
    additional_minute smallint NOT NULL,
    action_id character varying NOT NULL,
    match_id uuid NOT NULL,
    player_id uuid NOT NULL,
    CONSTRAINT match_matchevent_additional_minute_check CHECK ((additional_minute >= 0)),
    CONSTRAINT match_matchevent_minute_check CHECK ((minute >= 0))
);


ALTER TABLE public.match_matchevent OWNER TO fantasy_league;

--
-- Name: match_news; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.match_news (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    title character varying(100) NOT NULL,
    text text NOT NULL,
    photo character varying(200) NOT NULL
);


ALTER TABLE public.match_news OWNER TO fantasy_league;

--
-- Name: statistics_gameweekstats; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.statistics_gameweekstats (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    goals smallint NOT NULL,
    assists smallint NOT NULL,
    yellow_cards smallint NOT NULL,
    red_cards smallint NOT NULL,
    saves smallint NOT NULL,
    minutes smallint NOT NULL,
    own_goals smallint NOT NULL,
    penalties_saved smallint NOT NULL,
    penalties_missed smallint NOT NULL,
    goals_conceded smallint NOT NULL,
    clean_sheet boolean NOT NULL,
    gameweek_id uuid NOT NULL,
    player_id uuid NOT NULL,
    CONSTRAINT statistics_gameweekstats_assists_check CHECK ((assists >= 0)),
    CONSTRAINT statistics_gameweekstats_goals_check CHECK ((goals >= 0)),
    CONSTRAINT statistics_gameweekstats_goals_conceded_check CHECK ((goals_conceded >= 0)),
    CONSTRAINT statistics_gameweekstats_minutes_check CHECK ((minutes >= 0)),
    CONSTRAINT statistics_gameweekstats_own_goals_check CHECK ((own_goals >= 0)),
    CONSTRAINT statistics_gameweekstats_penalties_missed_check CHECK ((penalties_missed >= 0)),
    CONSTRAINT statistics_gameweekstats_penalties_saved_check CHECK ((penalties_saved >= 0)),
    CONSTRAINT statistics_gameweekstats_red_cards_check CHECK ((red_cards >= 0)),
    CONSTRAINT statistics_gameweekstats_saves_check CHECK ((saves >= 0)),
    CONSTRAINT statistics_gameweekstats_yellow_cards_check CHECK ((yellow_cards >= 0))
);


ALTER TABLE public.statistics_gameweekstats OWNER TO fantasy_league;

--
-- Name: team_club; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_club (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    short_name character varying(3) NOT NULL,
    code_name character varying(255) NOT NULL,
    logo character varying(100),
    logo_url character varying(200) NOT NULL,
    t_shirt_logo character varying(100),
    t_shirt_logo_url character varying(200) NOT NULL,
    played smallint NOT NULL,
    wins smallint NOT NULL,
    losses smallint NOT NULL,
    draws smallint NOT NULL,
    goals_for smallint NOT NULL,
    goals_against smallint NOT NULL,
    CONSTRAINT team_club_draws_check CHECK ((draws >= 0)),
    CONSTRAINT team_club_goals_against_check CHECK ((goals_against >= 0)),
    CONSTRAINT team_club_goals_for_check CHECK ((goals_for >= 0)),
    CONSTRAINT team_club_losses_check CHECK ((losses >= 0)),
    CONSTRAINT team_club_played_check CHECK ((played >= 0)),
    CONSTRAINT team_club_wins_check CHECK ((wins >= 0))
);


ALTER TABLE public.team_club OWNER TO fantasy_league;

--
-- Name: team_clubinfo; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_clubinfo (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    foundation_date date NOT NULL,
    stadium character varying(255) NOT NULL,
    stadium_capacity integer NOT NULL,
    info text NOT NULL,
    site_link character varying(200) NOT NULL,
    club_id character varying(255) NOT NULL,
    CONSTRAINT team_clubinfo_stadium_capacity_check CHECK ((stadium_capacity >= 0))
);


ALTER TABLE public.team_clubinfo OWNER TO fantasy_league;

--
-- Name: team_clubinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.team_clubinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_clubinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_communityleague; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_communityleague (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(255) NOT NULL,
    code_name character varying(255) NOT NULL
);


ALTER TABLE public.team_communityleague OWNER TO fantasy_league;

--
-- Name: team_communityleaguemembers; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_communityleaguemembers (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    league_id character varying(255) NOT NULL,
    team_id uuid NOT NULL
);


ALTER TABLE public.team_communityleaguemembers OWNER TO fantasy_league;

--
-- Name: team_communityleaguemembers_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.team_communityleaguemembers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_communityleaguemembers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_player; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_player (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    "position" character varying(255) NOT NULL,
    cost numeric(5,2) NOT NULL,
    club_id character varying(255) NOT NULL,
    card_image character varying(100),
    card_image_link character varying(200),
    t_short_number smallint,
    CONSTRAINT team_player_t_short_number_check CHECK ((t_short_number >= 0))
);


ALTER TABLE public.team_player OWNER TO fantasy_league;

--
-- Name: team_team; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_team (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    name character varying(255) NOT NULL,
    points smallint NOT NULL,
    profile_id uuid NOT NULL,
    CONSTRAINT team_team_points_check CHECK ((points >= 0))
);


ALTER TABLE public.team_team OWNER TO fantasy_league;

--
-- Name: team_teamplayer; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.team_teamplayer (
    id bigint NOT NULL,
    is_captain boolean NOT NULL,
    is_starter boolean NOT NULL,
    player_id uuid NOT NULL,
    team_id uuid NOT NULL
);


ALTER TABLE public.team_teamplayer OWNER TO fantasy_league;

--
-- Name: team_teamplayer_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.team_teamplayer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_teamplayer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.user_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    username character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    uuid uuid NOT NULL,
    deleted_at timestamp with time zone,
    md5_password character varying(32)
);


ALTER TABLE public.user_user OWNER TO fantasy_league;

--
-- Name: user_user_groups; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.user_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.user_user_groups OWNER TO fantasy_league;

--
-- Name: user_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.user_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.user_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_user_user_permissions; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.user_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.user_user_user_permissions OWNER TO fantasy_league;

--
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy_league
--

ALTER TABLE public.user_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_userprofile; Type: TABLE; Schema: public; Owner: fantasy_league
--

CREATE TABLE public.user_userprofile (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    email character varying(254),
    budget numeric(5,2) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_userprofile OWNER TO fantasy_league;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add permission	1	add_permission
2	Can change permission	1	change_permission
3	Can delete permission	1	delete_permission
4	Can view permission	1	view_permission
5	Can add group	2	add_group
6	Can change group	2	change_group
7	Can delete group	2	delete_group
8	Can view group	2	view_group
9	Can add content type	3	add_contenttype
10	Can change content type	3	change_contenttype
11	Can delete content type	3	delete_contenttype
12	Can view content type	3	view_contenttype
13	Can add session	4	add_session
14	Can change session	4	change_session
15	Can delete session	4	delete_session
16	Can view session	4	view_session
17	Can add user	5	add_user
18	Can change user	5	change_user
19	Can delete user	5	delete_user
20	Can view user	5	view_user
21	Can add Staff user	6	add_staffuser
22	Can change Staff user	6	change_staffuser
23	Can delete Staff user	6	delete_staffuser
24	Can view Staff user	6	view_staffuser
25	Extended session age	6	extended_session_age
26	Can add user profile	7	add_userprofile
27	Can change user profile	7	change_userprofile
28	Can delete user profile	7	delete_userprofile
29	Can view user profile	7	view_userprofile
30	Can add log entry	8	add_logentry
31	Can change log entry	8	change_logentry
32	Can delete log entry	8	delete_logentry
33	Can view log entry	8	view_logentry
34	Can add club	9	add_club
35	Can change club	9	change_club
36	Can delete club	9	delete_club
37	Can view club	9	view_club
38	Can add player	10	add_player
39	Can change player	10	change_player
40	Can delete player	10	delete_player
41	Can view player	10	view_player
42	Can add team	11	add_team
43	Can change team	11	change_team
44	Can delete team	11	delete_team
45	Can view team	11	view_team
46	Can add team player	12	add_teamplayer
47	Can change team player	12	change_teamplayer
48	Can delete team player	12	delete_teamplayer
49	Can view team player	12	view_teamplayer
50	Can add club info	13	add_clubinfo
51	Can change club info	13	change_clubinfo
52	Can delete club info	13	delete_clubinfo
53	Can view club info	13	view_clubinfo
54	Can add match event	14	add_matchevent
55	Can change match event	14	change_matchevent
56	Can delete match event	14	delete_matchevent
57	Can view match event	14	view_matchevent
58	Can add match	15	add_match
59	Can change match	15	change_match
60	Can delete match	15	delete_match
61	Can view match	15	view_match
62	Can add game week	16	add_gameweek
63	Can change game week	16	change_gameweek
64	Can delete game week	16	delete_gameweek
65	Can view game week	16	view_gameweek
66	Can add line up	17	add_lineup
67	Can change line up	17	change_lineup
68	Can delete line up	17	delete_lineup
69	Can view line up	17	view_lineup
70	Can add game week stats	18	add_gameweekstats
71	Can change game week stats	18	change_gameweekstats
72	Can delete game week stats	18	delete_gameweekstats
73	Can view game week stats	18	view_gameweekstats
74	Can add match action	19	add_matchaction
75	Can change match action	19	change_matchaction
76	Can delete match action	19	delete_matchaction
77	Can view match action	19	view_matchaction
78	Can add community league members	20	add_communityleaguemembers
79	Can change community league members	20	change_communityleaguemembers
80	Can delete community league members	20	delete_communityleaguemembers
81	Can view community league members	20	view_communityleaguemembers
82	Can add community league	21	add_communityleague
83	Can change community league	21	change_communityleague
84	Can delete community league	21	delete_communityleague
85	Can view community league	21	view_communityleague
86	Can add news	22	add_news
87	Can change news	22	change_news
88	Can delete news	22	delete_news
89	Can view news	22	view_news
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-20 12:37:53.641009+00	minsk	Club object (minsk)	1	[{"added": {}}]	9	2
2	2025-04-20 12:38:47.73914+00	arsenal	Club object (arsenal)	1	[{"added": {}}]	9	2
3	2025-04-20 15:21:56.246236+00	1	ClubInfo object (1)	1	[{"added": {}}]	13	2
4	2025-04-20 15:24:54.66283+00	2	ClubInfo object (2)	1	[{"added": {}}]	13	2
5	2025-04-20 16:50:13.760382+00	isloch	Ислочь	1	[{"added": {}}]	9	2
6	2025-04-20 16:52:31.171212+00	smorgon	Cморгонь	1	[{"added": {}}]	9	2
7	2025-04-20 16:53:00.578988+00	dinamo-brest	Динамо-Брест	1	[{"added": {}}]	9	2
8	2025-04-20 16:55:13.619215+00	dinamo-minsk	Динамо-Минск	1	[{"added": {}}]	9	2
9	2025-04-20 16:56:18.966201+00	slutsk	Слуцк	1	[{"added": {}}]	9	2
10	2025-04-20 17:26:20.274627+00	arsenal	Арсенал	2	[{"changed": {"fields": ["Played", "Losses", "Draws", "Goals for", "Goals against"]}}]	9	2
11	2025-04-20 17:26:36.279238+00	dinamo-brest	Динамо-Брест	2	[{"changed": {"fields": ["Played", "Wins", "Draws", "Goals for", "Goals against"]}}]	9	2
12	2025-04-21 08:18:04.721241+00	maxline-vitebsk	МЛ Витебск	1	[{"added": {}}]	9	2
13	2025-04-21 08:18:39.998875+00	gomel	Гомель	1	[{"added": {}}]	9	2
14	2025-04-22 15:09:28.1146+00	60b00664-ce7c-42e4-a801-329197f539d4	Player object (60b00664-ce7c-42e4-a801-329197f539d4)	1	[{"added": {}}]	10	2
15	2025-04-22 15:10:14.777365+00	ac9bb7eb-9688-487d-9585-bef5bfbda800	Player object (ac9bb7eb-9688-487d-9585-bef5bfbda800)	1	[{"added": {}}]	10	2
16	2025-04-22 15:11:17.467729+00	3aecd5da-cf32-47fa-bd58-905f424e6a76	Player object (3aecd5da-cf32-47fa-bd58-905f424e6a76)	1	[{"added": {}}]	10	2
17	2025-04-22 15:11:53.203747+00	05bcbe76-eb91-44e1-b950-bd7706c90b41	Player object (05bcbe76-eb91-44e1-b950-bd7706c90b41)	1	[{"added": {}}]	10	2
18	2025-04-23 11:47:50.558663+00	25a52224-6ae2-4573-b0a0-029d05c7b632	GameWeek object (25a52224-6ae2-4573-b0a0-029d05c7b632)	1	[{"added": {}}]	16	2
19	2025-04-23 11:48:06.254798+00	bac92aa4-831f-410c-a8da-2d9c4e37a75d	GameWeek object (bac92aa4-831f-410c-a8da-2d9c4e37a75d)	1	[{"added": {}}]	16	2
20	2025-04-23 12:01:18.297188+00	6e9850af-bc17-4636-98b6-ff68c150b96b	2025-04-05 18:00:00+00:00: Ислочь - Минск	1	[{"added": {}}, {"added": {"name": "line up", "object": "LineUp object (fe6f344c-fccd-4713-84fc-5b44a1587b15)"}}, {"added": {"name": "line up", "object": "LineUp object (abcf67a2-87e9-417f-ba46-a44fedd4bd6f)"}}, {"added": {"name": "line up", "object": "LineUp object (75bd5f96-46d1-4adb-82ff-edfcb3ab6a7d)"}}, {"added": {"name": "line up", "object": "LineUp object (acfbb9ad-4965-49ac-abac-dac9fa018613)"}}, {"added": {"name": "match event", "object": "MatchEvent object (76deef43-79f1-40d7-b4e6-3e7d65a5177c)"}}, {"added": {"name": "match event", "object": "MatchEvent object (39289517-3254-4bd5-87c9-21eee9741e91)"}}, {"added": {"name": "match event", "object": "MatchEvent object (399e10bb-c2fd-4507-a2ed-28b9d5a2c65a)"}}, {"added": {"name": "match event", "object": "MatchEvent object (ebeae672-0569-42ba-b83e-274b3f8a63b5)"}}, {"added": {"name": "match event", "object": "MatchEvent object (9ee147f7-c8ad-4dbf-acd8-f558cd6f2ee3)"}}]	15	2
21	2025-04-25 11:43:40.861532+00	c3dee51a-7dff-4360-9f90-f14dda3c3cbb	2025-04-06 16:00:00+00:00: МЛ Витебск - Минск	1	[{"added": {}}]	15	2
22	2025-04-25 11:44:10.013605+00	f5a8f11b-7f8a-474c-a1a1-3bab045f5a72	2025-04-06 20:00:00+00:00: Гомель - Слуцк	1	[{"added": {}}]	15	2
23	2025-04-25 11:46:00.594186+00	764c3b37-032b-4763-97cd-5c00b8a261d9	2025-04-12 17:30:00+00:00: Динамо-Брест - Динамо-Минск	1	[{"added": {}}]	15	2
24	2025-04-25 12:39:00.985022+00	12bdec39-2820-4963-86cd-c9a8fe27d4a9	Андрей Климович (gkp) - Ислочь	1	[{"added": {}}]	10	2
25	2025-04-25 12:39:53.146514+00	fd40d348-2787-4eff-af43-13cfc072a01f	Кирилл Родионов (def) - Ислочь	1	[{"added": {}}]	10	2
26	2025-04-25 12:40:19.449483+00	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	Иван Тихомиров (def) - Ислочь	1	[{"added": {}}]	10	2
27	2025-04-25 12:41:03.175635+00	6e9850af-bc17-4636-98b6-ff68c150b96b	2025-04-05 18:00:00+00:00: Ислочь - Минск	2	[{"added": {"name": "line up", "object": "LineUp object (23754da9-40b0-4d15-85ed-7e8e6ba0bd25)"}}, {"added": {"name": "line up", "object": "LineUp object (4c94821f-70a2-40b9-9bd6-7958e2e41141)"}}, {"added": {"name": "line up", "object": "LineUp object (ae5dde22-1ec8-45d6-a769-fdccbe6536ac)"}}, {"changed": {"name": "match event", "object": "MatchEvent object (399e10bb-c2fd-4507-a2ed-28b9d5a2c65a)", "fields": ["Player"]}}]	15	2
28	2025-04-27 20:40:06.802009+00	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	Иван Тихомиров (def) - Ислочь	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
29	2025-04-27 20:41:03.084012+00	05bcbe76-eb91-44e1-b950-bd7706c90b41	Евгений Юдчиц (def) - Ислочь	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
30	2025-04-27 20:41:14.198364+00	12bdec39-2820-4963-86cd-c9a8fe27d4a9	Андрей Климович (gkp) - Ислочь	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
31	2025-04-27 20:42:26.169458+00	3aecd5da-cf32-47fa-bd58-905f424e6a76	Александр Свирский (gkp) - Ислочь	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
32	2025-04-27 20:42:38.231253+00	fd40d348-2787-4eff-af43-13cfc072a01f	Кирилл Родионов (def) - Ислочь	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
33	2025-04-27 20:43:00.118964+00	ac9bb7eb-9688-487d-9585-bef5bfbda800	Руслан Хадаркевич (def) - Минск	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
34	2025-04-27 20:43:50.146144+00	60b00664-ce7c-42e4-a801-329197f539d4	Александр Гутор (gkp) - Минск	2	[{"changed": {"fields": ["T short number", "Card image link"]}}]	10	2
35	2025-04-27 21:27:27.867698+00	goal	Goal	1	[{"added": {}}]	19	2
36	2025-04-27 21:28:03.023294+00	assist	Assist	1	[{"added": {}}]	19	2
37	2025-04-27 21:29:18.723703+00	yellow_card	Yellow card	1	[{"added": {}}]	19	2
38	2025-04-27 21:29:39.638654+00	red_card	Red card	1	[{"added": {}}]	19	2
39	2025-04-27 21:30:25.066335+00	sub_on	Sub on	1	[{"added": {}}]	19	2
40	2025-04-27 21:31:12.609951+00	sub_off	Sub off	1	[{"added": {}}]	19	2
41	2025-04-27 21:31:52.170222+00	own_goal	Own goal	1	[{"added": {}}]	19	2
42	2025-04-27 21:32:05.630787+00	penalty_save	Penalty save	1	[{"added": {}}]	19	2
43	2025-04-27 21:32:16.833369+00	penalty_miss	Penalty miss	1	[{"added": {}}]	19	2
44	2025-04-27 21:33:07.494992+00	save	Save	1	[{"added": {}}]	19	2
45	2025-04-27 21:33:52.405101+00	penalty_save	Penalty save	2	[{"changed": {"fields": ["For display"]}}]	19	2
46	2025-04-27 21:40:39.014861+00	6e9850af-bc17-4636-98b6-ff68c150b96b	2025-04-05 18:00:00+00:00: Ислочь - Минск	2	[{"added": {"name": "match event", "object": "MatchEvent object (1aa30463-e42a-4324-a50c-7eda9482d65a)"}}, {"added": {"name": "match event", "object": "MatchEvent object (1b6bcd5d-fe10-47f0-93bf-4541b3d042d3)"}}, {"added": {"name": "match event", "object": "MatchEvent object (2fb7f3b3-fe42-4654-bfef-47d0a8e2df61)"}}, {"added": {"name": "match event", "object": "MatchEvent object (27152079-29e3-4999-b4d0-4eb3de2fb189)"}}, {"added": {"name": "match event", "object": "MatchEvent object (4a821984-7249-4aa7-82ec-ae029afc8cc4)"}}, {"added": {"name": "match event", "object": "MatchEvent object (a7f47887-e066-42cf-948b-a32957059ce6)"}}]	15	2
47	2025-04-28 09:02:22.161359+00	6e9850af-bc17-4636-98b6-ff68c150b96b	2025-04-05 18:00:00+00:00: Ислочь - Минск	2	[{"added": {"name": "match event", "object": "MatchEvent object (00fe2a75-f863-4caa-b804-aca45348dd72)"}}]	15	2
48	2025-04-28 19:57:56.573931+00	165b0892-1834-4336-9ce5-8b839f4aa8a2	2025-05-07 18:00:00+00:00: Слуцк - Cморгонь	1	[{"added": {}}]	15	2
49	2025-04-28 20:07:27.866999+00	a4ff5c71-06fa-4bb8-a152-fb2ca053c360	3: 2025-05-08 20:07:21+00:00 - 2025-05-14 20:07:27+00:00	1	[{"added": {}}]	16	2
50	2025-04-28 20:07:52.138359+00	37a23397-c214-4404-a999-50a2b4549a76	2025-05-11 20:00:00+00:00: Динамо-Минск - МЛ Витебск	1	[{"added": {}}]	15	2
51	2025-04-28 20:08:17.350869+00	fc41832d-704a-4077-8d89-3256a155a4e9	2025-05-15 18:00:00+00:00: Гомель - Ислочь	1	[{"added": {}}]	15	2
52	2025-04-28 20:08:53.993238+00	fc41832d-704a-4077-8d89-3256a155a4e9	2025-05-15 18:00:00+00:00: Гомель - Ислочь	2	[{"changed": {"fields": ["Gameweek"]}}]	15	2
53	2025-04-28 20:09:03.850082+00	37a23397-c214-4404-a999-50a2b4549a76	2025-05-11 20:00:00+00:00: Динамо-Минск - МЛ Витебск	2	[{"changed": {"fields": ["Gameweek"]}}]	15	2
54	2025-05-01 11:50:03.404712+00	fc41832d-704a-4077-8d89-3256a155a4e9	2025-05-15 18:00:00+00:00: Гомель - Ислочь	2	[{"added": {"name": "line up", "object": "LineUp object (6a235a07-da9a-49cd-a782-4b002c651f77)"}}, {"added": {"name": "line up", "object": "LineUp object (41f3a267-a764-4b54-8dd7-ebb7a4356bbf)"}}, {"added": {"name": "line up", "object": "LineUp object (d75c187a-1486-4096-adaf-8857f04c1a9c)"}}]	15	2
55	2025-05-04 15:17:06.350786+00	eb644324-2ff4-4295-bbd2-c9ba1a0be15d	Артем Сороко (gkp) - Арсенал	1	[{"added": {}}]	10	2
56	2025-05-04 15:17:43.472221+00	19a79a7b-f143-4572-b1c8-047a3b0bf281	Иван Санько (gkp) - Арсенал	1	[{"added": {}}]	10	2
57	2025-05-04 15:18:46.268966+00	862ef733-39be-4af4-b669-731f8724ff86	Кирилл Волков (def) - Арсенал	1	[{"added": {}}]	10	2
58	2025-05-04 15:19:21.436905+00	be063b12-15e1-4d80-87f4-2d6e3d6cff7f	Александр Михаленко (def) - Арсенал	1	[{"added": {}}]	10	2
59	2025-05-04 15:22:02.919017+00	a53fddff-7078-4232-b794-68dd9d160dff	Глеб Якушевич (def) - Арсенал	1	[{"added": {}}]	10	2
60	2025-05-04 15:23:44.68511+00	f24e9b1b-529a-44d8-9529-7b000f304736	Михаил Козакевич (gkp) - Динамо-Брест	1	[{"added": {}}]	10	2
61	2025-05-04 15:24:18.030812+00	33fa37b6-0ab1-458d-aa2b-5e47bb50ab0d	Дмитрий Дударь (gkp) - Динамо-Брест	1	[{"added": {}}]	10	2
62	2025-05-04 15:24:54.427037+00	917bd825-69bb-4bb0-80cc-d5d4425f66c6	Артем Рахманов (def) - Динамо-Брест	1	[{"added": {}}]	10	2
63	2025-05-04 15:27:27.116852+00	e2d31898-257d-4c2b-991d-6537aa1a21fd	Максим Касараб (def) - Динамо-Брест	1	[{"added": {}}]	10	2
64	2025-05-04 15:28:03.782814+00	007cf653-6d56-4a55-ad03-6e0715d2f864	Артем Быков (mid) - Динамо-Брест	1	[{"added": {}}]	10	2
65	2025-05-04 17:48:11.41621+00	8c7a92a3-d7f7-4569-b258-dc248416a8d5	Артем Турич (mid) - Динамо-Брест	1	[{"added": {}}]	10	2
66	2025-05-04 17:52:01.137355+00	96d94865-df4f-465c-9cdd-09b44db06783	Михаил Гордейчук (mid) - Динамо-Брест	1	[{"added": {}}]	10	2
67	2025-05-04 17:57:54.009612+00	4c46f54c-3c4b-4266-af78-d61eebaf14b2	Евгений Малашевич (mid) - Динамо-Минск	1	[{"added": {}}]	10	2
68	2025-05-04 17:58:30.315092+00	7e5f9082-60f3-476e-afb6-3dad1b69add3	Евгений Шевченко (mid) - Динамо-Минск	1	[{"added": {}}]	10	2
69	2025-05-04 18:00:20.460144+00	0f27853b-3306-4f9b-9bf7-6c644529e5a2	Иван Бахар (mid) - Динамо-Минск	1	[{"added": {}}]	10	2
70	2025-05-04 18:00:39.021725+00	0f27853b-3306-4f9b-9bf7-6c644529e5a2	Иван Бахар (fwd) - Динамо-Минск	2	[{"changed": {"fields": ["Position"]}}]	10	2
71	2025-05-04 18:01:28.348497+00	4d685dbb-d391-433a-9703-5b9350e0c059	Денис Козловский (fwd) - МЛ Витебск	1	[{"added": {}}]	10	2
72	2025-05-04 18:05:08.856932+00	48c9f281-857a-4324-95ec-32c174395601	Денис Овсянников (fwd) - МЛ Витебск	1	[{"added": {}}]	10	2
73	2025-05-07 08:00:00.557398+00	arsenal	Арсенал	2	[{"changed": {"fields": ["Logo url", "T shirt logo url"]}}]	9	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	auth	permission
2	auth	group
3	contenttypes	contenttype
4	sessions	session
5	user	user
6	user	staffuser
7	user	userprofile
8	admin	logentry
9	team	club
10	team	player
11	team	team
12	team	teamplayer
13	team	clubinfo
14	match	matchevent
15	match	match
16	match	gameweek
17	match	lineup
18	statistics	gameweekstats
19	match	matchaction
20	team	communityleaguemembers
21	team	communityleague
22	match	news
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-16 12:53:04.27266+00
2	contenttypes	0002_remove_content_type_name	2025-04-16 12:53:04.277749+00
3	auth	0001_initial	2025-04-16 12:53:04.314129+00
4	auth	0002_alter_permission_name_max_length	2025-04-16 12:53:04.31802+00
5	auth	0003_alter_user_email_max_length	2025-04-16 12:53:04.322616+00
6	auth	0004_alter_user_username_opts	2025-04-16 12:53:04.327105+00
7	auth	0005_alter_user_last_login_null	2025-04-16 12:53:04.333611+00
8	auth	0006_require_contenttypes_0002	2025-04-16 12:53:04.335652+00
9	auth	0007_alter_validators_add_error_messages	2025-04-16 12:53:04.37578+00
10	auth	0008_alter_user_username_max_length	2025-04-16 12:53:04.381814+00
11	auth	0009_alter_user_last_name_max_length	2025-04-16 12:53:04.387879+00
12	auth	0010_alter_group_name_max_length	2025-04-16 12:53:04.394627+00
13	auth	0011_update_proxy_permissions	2025-04-16 12:53:04.400516+00
14	auth	0012_alter_user_first_name_max_length	2025-04-16 12:53:04.40683+00
15	sessions	0001_initial	2025-04-16 12:53:04.422424+00
16	user	0001_initial	2025-04-16 12:53:04.475333+00
17	admin	0001_initial	2025-04-16 13:04:24.701954+00
18	admin	0002_logentry_remove_auto_add	2025-04-16 13:04:24.735492+00
19	admin	0003_logentry_add_action_flag_choices	2025-04-16 13:04:24.743553+00
20	team	0001_initial	2025-04-19 10:59:59.867333+00
21	team	0002_clubinfo	2025-04-20 15:20:40.753522+00
22	team	0003_alter_clubinfo_club	2025-04-20 15:31:47.372318+00
23	team	0004_alter_clubinfo_club	2025-04-20 15:32:34.980001+00
24	user	0002_alter_userprofile_email	2025-04-21 08:10:36.13014+00
25	match	0001_initial	2025-04-22 15:07:05.244445+00
26	statistics	0001_initial	2025-04-22 15:07:05.272135+00
27	match	0002_alter_matchevent_additional_minute	2025-04-23 11:57:30.495759+00
28	match	0003_remove_match_processed	2025-04-25 07:50:20.791808+00
29	team	0005_player_card_image_player_card_image_link_and_more	2025-04-27 20:06:12.393691+00
30	match	0004_matchaction_remove_matchevent_for_display_and_more	2025-04-27 21:22:12.250782+00
31	match	0005_news	2025-05-26 08:08:07.139443+00
32	team	0006_communityleague_communityleaguemembers	2025-05-26 08:08:07.179554+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
wgm2wiaro16yb5m6lvx1mjl8ch0trbdi	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1u52Tb:3GDSbOtvkjSLP3Af8Os14bKjh-8l3qpPqZuxO3qUaek	2025-04-30 13:06:51.809053+00
n7v6e6t5xuz1jt5ffenqn7usqbpd0tk6	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1u677t:G2Z7fGSQZ4zvzQTtLqBudrtN_BTauNiYTlSwVvOZ2UI	2025-05-03 12:16:53.072696+00
kiciq1fx3tp3svyg876b51hdzqaazqu4	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1u7FE7:VXhif3cb0-XO52GaMjNkBH0vxg1fG0YVYwnS0QOdyGQ	2025-05-06 15:07:59.943353+00
2kbhc78ijnst108n1qyl3zbq54wqaypi	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1uCZgz:fdbCcPU2Jz_Pb-QyHjZP3jfhVx7MOpHSHyuEqXPQtsA	2025-05-21 07:59:49.610387+00
wy2hxebkjs82han5ymbpgd5jt2i4tgzf	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1uIBBX:RfnlT6ghEHsW6OzQanRqP0mBBm0TXQiVWvoFn5w4MRY	2025-06-05 19:02:31.178026+00
e6zalkl2135xz89pvrlw2bjhkeui0vi9	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1uNS65:6PCQ9nFGccNfO3ZVTfQpxAsHq5VQmAthnFHRXwdsCuQ	2025-06-20 08:06:41.958558+00
lt7v312zdbi15zo1jyg6blpf8lo10xu1	.eJxVizsOwjAQBe_iGkUm_uyGkp4zWBvvs4xAIOGkQtydWEoB5Zt58zZJ1qWmteGVrmpOZjSHXzZLvuHRRZ9DF8PO2nB5Ku7n_fGXVWl1azhHikfxELBDRLYEURZCUGY7jQoNxU9uZm8Z0W1eqbBXSxSKms8XjP00iA:1uQ1Ko:TGtiNHITB_8Jijg4yY0VtPWDNWnEzjguNsE9v82EraM	2025-06-27 10:08:30.770784+00
\.


--
-- Data for Name: match_gameweek; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_gameweek (created_at, updated_at, id, number, actual_from, actual_to) FROM stdin;
2025-04-23 11:47:50.556573+00	2025-04-23 11:47:50.556595+00	25a52224-6ae2-4573-b0a0-029d05c7b632	1	2025-04-01 00:00:00+00	2025-04-07 00:00:00+00
2025-04-23 11:48:06.252637+00	2025-04-23 11:48:06.252668+00	bac92aa4-831f-410c-a8da-2d9c4e37a75d	2	2025-04-23 11:48:00+00	2025-05-14 11:48:04+00
2025-04-28 20:07:27.865101+00	2025-04-28 20:07:27.86513+00	a4ff5c71-06fa-4bb8-a152-fb2ca053c360	3	2025-05-08 20:07:21+00	2025-05-14 20:07:27+00
\.


--
-- Data for Name: match_lineup; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_lineup (created_at, updated_at, id, in_start, player_id, match_id) FROM stdin;
2025-04-23 12:01:18.289733+00	2025-04-23 12:01:18.28975+00	fe6f344c-fccd-4713-84fc-5b44a1587b15	t	60b00664-ce7c-42e4-a801-329197f539d4	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-23 12:01:18.290411+00	2025-04-23 12:01:18.290424+00	abcf67a2-87e9-417f-ba46-a44fedd4bd6f	t	ac9bb7eb-9688-487d-9585-bef5bfbda800	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-23 12:01:18.290881+00	2025-04-23 12:01:18.290897+00	75bd5f96-46d1-4adb-82ff-edfcb3ab6a7d	t	3aecd5da-cf32-47fa-bd58-905f424e6a76	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-23 12:01:18.291456+00	2025-04-23 12:01:18.291471+00	acfbb9ad-4965-49ac-abac-dac9fa018613	f	05bcbe76-eb91-44e1-b950-bd7706c90b41	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-25 12:41:03.172395+00	2025-04-25 12:41:03.172415+00	23754da9-40b0-4d15-85ed-7e8e6ba0bd25	f	12bdec39-2820-4963-86cd-c9a8fe27d4a9	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-25 12:41:03.173263+00	2025-04-25 12:41:03.173275+00	4c94821f-70a2-40b9-9bd6-7958e2e41141	t	fd40d348-2787-4eff-af43-13cfc072a01f	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-04-25 12:41:03.173667+00	2025-04-25 12:41:03.173677+00	ae5dde22-1ec8-45d6-a769-fdccbe6536ac	t	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	6e9850af-bc17-4636-98b6-ff68c150b96b
2025-05-01 11:50:03.400836+00	2025-05-01 11:50:03.400943+00	6a235a07-da9a-49cd-a782-4b002c651f77	t	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	fc41832d-704a-4077-8d89-3256a155a4e9
2025-05-01 11:50:03.402993+00	2025-05-01 11:50:03.403012+00	41f3a267-a764-4b54-8dd7-ebb7a4356bbf	t	fd40d348-2787-4eff-af43-13cfc072a01f	fc41832d-704a-4077-8d89-3256a155a4e9
2025-05-01 11:50:03.403553+00	2025-05-01 11:50:03.403565+00	d75c187a-1486-4096-adaf-8857f04c1a9c	f	12bdec39-2820-4963-86cd-c9a8fe27d4a9	fc41832d-704a-4077-8d89-3256a155a4e9
\.


--
-- Data for Name: match_match; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_match (created_at, updated_at, id, home_club_goals, away_club_goals, start_time, full_time, away_club_id, gameweek_id, home_club_id) FROM stdin;
2025-04-25 11:43:40.859609+00	2025-04-25 11:43:40.859631+00	c3dee51a-7dff-4360-9f90-f14dda3c3cbb	3	1	2025-04-06 16:00:00+00	t	minsk	25a52224-6ae2-4573-b0a0-029d05c7b632	maxline-vitebsk
2025-04-25 11:44:10.012198+00	2025-04-25 11:44:10.012251+00	f5a8f11b-7f8a-474c-a1a1-3bab045f5a72	0	0	2025-04-06 20:00:00+00	t	slutsk	25a52224-6ae2-4573-b0a0-029d05c7b632	gomel
2025-04-25 11:46:00.592797+00	2025-04-25 11:46:00.592816+00	764c3b37-032b-4763-97cd-5c00b8a261d9	2	2	2025-04-12 17:30:00+00	t	dinamo-minsk	bac92aa4-831f-410c-a8da-2d9c4e37a75d	dinamo-brest
2025-04-23 12:01:18.288652+00	2025-04-28 09:02:22.155741+00	6e9850af-bc17-4636-98b6-ff68c150b96b	1	1	2025-04-05 18:00:00+00	t	minsk	25a52224-6ae2-4573-b0a0-029d05c7b632	isloch
2025-04-28 19:57:56.568927+00	2025-04-28 19:57:56.568949+00	165b0892-1834-4336-9ce5-8b839f4aa8a2	0	0	2025-05-07 18:00:00+00	f	smorgon	bac92aa4-831f-410c-a8da-2d9c4e37a75d	slutsk
2025-04-28 20:07:52.137081+00	2025-04-28 20:09:03.848214+00	37a23397-c214-4404-a999-50a2b4549a76	0	0	2025-05-11 20:00:00+00	f	maxline-vitebsk	a4ff5c71-06fa-4bb8-a152-fb2ca053c360	dinamo-minsk
2025-04-28 20:08:17.349016+00	2025-05-01 11:50:03.396261+00	fc41832d-704a-4077-8d89-3256a155a4e9	0	0	2025-05-15 18:00:00+00	f	isloch	a4ff5c71-06fa-4bb8-a152-fb2ca053c360	gomel
\.


--
-- Data for Name: match_matchaction; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_matchaction (created_at, updated_at, code, name, for_display) FROM stdin;
2025-04-27 21:27:27.86683+00	2025-04-27 21:27:27.866844+00	goal	Goal	t
2025-04-27 21:28:03.022693+00	2025-04-27 21:28:03.022707+00	assist	Assist	t
2025-04-27 21:29:18.72296+00	2025-04-27 21:29:18.722984+00	yellow_card	Yellow card	t
2025-04-27 21:29:39.638084+00	2025-04-27 21:29:39.638098+00	red_card	Red card	t
2025-04-27 21:30:25.065745+00	2025-04-27 21:30:25.065759+00	sub_on	Sub on	t
2025-04-27 21:31:12.609347+00	2025-04-27 21:31:12.609364+00	sub_off	Sub off	t
2025-04-27 21:31:52.169642+00	2025-04-27 21:31:52.169658+00	own_goal	Own goal	t
2025-04-27 21:32:16.832627+00	2025-04-27 21:32:16.832644+00	penalty_miss	Penalty miss	t
2025-04-27 21:33:07.494436+00	2025-04-27 21:33:07.494455+00	save	Save	f
2025-04-27 21:32:05.630043+00	2025-04-27 21:33:52.403823+00	penalty_save	Penalty save	f
\.


--
-- Data for Name: match_matchevent; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_matchevent (created_at, updated_at, id, minute, additional_minute, action_id, match_id, player_id) FROM stdin;
2025-04-27 21:40:39.009321+00	2025-04-27 21:40:39.009343+00	1aa30463-e42a-4324-a50c-7eda9482d65a	12	0	goal	6e9850af-bc17-4636-98b6-ff68c150b96b	ac9bb7eb-9688-487d-9585-bef5bfbda800
2025-04-27 21:40:39.010996+00	2025-04-27 21:40:39.011017+00	1b6bcd5d-fe10-47f0-93bf-4541b3d042d3	53	0	sub_on	6e9850af-bc17-4636-98b6-ff68c150b96b	05bcbe76-eb91-44e1-b950-bd7706c90b41
2025-04-27 21:40:39.01158+00	2025-04-27 21:40:39.011591+00	2fb7f3b3-fe42-4654-bfef-47d0a8e2df61	53	0	sub_off	6e9850af-bc17-4636-98b6-ff68c150b96b	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e
2025-04-27 21:40:39.01219+00	2025-04-27 21:40:39.01221+00	27152079-29e3-4999-b4d0-4eb3de2fb189	77	0	goal	6e9850af-bc17-4636-98b6-ff68c150b96b	05bcbe76-eb91-44e1-b950-bd7706c90b41
2025-04-27 21:40:39.013003+00	2025-04-27 21:40:39.013021+00	4a821984-7249-4aa7-82ec-ae029afc8cc4	77	0	assist	6e9850af-bc17-4636-98b6-ff68c150b96b	fd40d348-2787-4eff-af43-13cfc072a01f
2025-04-27 21:40:39.013824+00	2025-04-27 21:40:39.01384+00	a7f47887-e066-42cf-948b-a32957059ce6	89	0	yellow_card	6e9850af-bc17-4636-98b6-ff68c150b96b	60b00664-ce7c-42e4-a801-329197f539d4
2025-04-28 09:02:22.158988+00	2025-04-28 09:02:22.159023+00	00fe2a75-f863-4caa-b804-aca45348dd72	45	4	red_card	6e9850af-bc17-4636-98b6-ff68c150b96b	ac9bb7eb-9688-487d-9585-bef5bfbda800
\.


--
-- Data for Name: match_news; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.match_news (created_at, updated_at, id, title, text, photo) FROM stdin;
\.


--
-- Data for Name: statistics_gameweekstats; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.statistics_gameweekstats (created_at, updated_at, id, goals, assists, yellow_cards, red_cards, saves, minutes, own_goals, penalties_saved, penalties_missed, goals_conceded, clean_sheet, gameweek_id, player_id) FROM stdin;
\.


--
-- Data for Name: team_club; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_club (created_at, updated_at, name, short_name, code_name, logo, logo_url, t_shirt_logo, t_shirt_logo_url, played, wins, losses, draws, goals_for, goals_against) FROM stdin;
2025-04-20 12:37:53.638497+00	2025-04-20 12:37:53.638526+00	Минск	МНК	minsk		https://championship.abff.by/uploads/images/teams/6155bf01c019b665569103.png		https://championship.abff.by/uploads/images/teams/6155bf01c019b665569103.png	0	0	0	0	0	0
2025-04-20 16:50:13.759308+00	2025-04-20 16:50:13.759333+00	Ислочь	ИСЛ	isloch		https://championship.abff.by/uploads/images/teams/6155ca3d0ffba444922321.png		https://championship.abff.by/uploads/images/teams/6155ca3d0ffba444922321.png	0	0	0	0	0	0
2025-04-20 16:52:31.170044+00	2025-04-20 16:52:31.170068+00	Cморгонь	СМН	smorgon		https://championship.abff.by/uploads/images/teams/615af9f740b5e408998112.png		https://championship.abff.by/uploads/images/teams/615af9f740b5e408998112.png	0	0	0	0	0	0
2025-04-20 16:55:13.61814+00	2025-04-20 16:55:13.618165+00	Динамо-Минск	ДНМ	dinamo-minsk		https://championship.abff.by/uploads/images/teams/618a64e0cbf03465303381.png		https://championship.abff.by/uploads/images/teams/618a64e0cbf03465303381.png	0	0	0	0	0	0
2025-04-20 16:56:18.965204+00	2025-04-20 16:56:18.965223+00	Слуцк	СЛЦ	slutsk		https://championship.abff.by/uploads/images/teams/625428f6be1ef633547339.png		https://championship.abff.by/uploads/images/teams/625428f6be1ef633547339.png	0	0	0	0	0	0
2025-04-20 16:53:00.577712+00	2025-04-20 17:26:36.277406+00	Динамо-Брест	ДБР	dinamo-brest		https://championship.abff.by/uploads/images/teams/5acf4dfd52ccf.png		https://championship.abff.by/uploads/images/teams/5acf4dfd52ccf.png	3	2	0	1	9	8
2025-04-21 08:18:04.720307+00	2025-04-21 08:18:04.720323+00	МЛ Витебск	МЛВ	maxline-vitebsk		https://championship.abff.by/uploads/images/teams/67a9ce8606feb923373982.png		https://championship.abff.by/uploads/images/teams/67a9ce8606feb923373982.png	2	2	0	0	5	2
2025-04-21 08:18:39.997893+00	2025-04-21 08:18:39.997912+00	Гомель	ГОМ	gomel		https://championship.abff.by/uploads/images/teams/615af95dca38a374995232.png		https://championship.abff.by/uploads/images/teams/615af95dca38a374995232.png	3	1	1	1	4	4
2025-04-20 12:38:47.737607+00	2025-05-07 08:00:00.554039+00	Арсенал	АРС	arsenal		https://championship.abff.by/uploads/images/teams/681a03181ff35052468165.png		https://championship.abff.by/uploads/images/teams/681a03181ff35052468165.png	3	0	1	2	4	7
\.


--
-- Data for Name: team_clubinfo; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_clubinfo (id, created_at, updated_at, foundation_date, stadium, stadium_capacity, info, site_link, club_id) FROM stdin;
1	2025-04-20 15:21:56.244218+00	2025-04-20 15:21:56.244239+00	1954-04-08	ФК «Минск»	3000	В высшей лиге с сезона 2007 (кроме 2008).\r\n\r\nС началом суверенного этапа, команда «Смена» выступала в третьем дивизионе, однако не регулярно. На серьезную основу дело было поставлено в 2006 году, когда клуб обрел свое нынешнее название. Уже в 2007 «Минск» дебютировал в высшей лиге, правда, был отправлен обратно, работать над ошибками. Справившись с задачей, «горожане» закрепились в «элите», а уже в сезоне 2010 выиграли «бронзу». Вскоре со второй попытки был выигран Кубок страны и проведена хорошая еврокубковая кампания: лишь в раунде плей-офф «красно-синих» сумел остановить бельгийский «Стандард». В последние сезоны «Минск» стремится делать ставку на доморощенные кадры, что и логично: клуб обладает большой школой с весьма развитой инфраструктурой.	https://fcminsk.by/	minsk
2	2025-04-20 15:24:54.66115+00	2025-04-20 15:24:54.661171+00	2018-04-06	«Городея»	1625	Клуб был создан в 2018 году. Свой первый сезон в 2019 году «Арсенал» провел во Второй лиге, выступление в которой принесло команде Чемпионство. Закрепившись в Первой лиге в сезоне 2020 года, команда под руководством Павла Кирильчика выиграла турнир уже в следующем сезоне и завоевала путевку в элитный дивизион.	https://vk.com/arsenaldzerzhinsk	arsenal
\.


--
-- Data for Name: team_communityleague; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_communityleague (created_at, updated_at, name, code_name) FROM stdin;
\.


--
-- Data for Name: team_communityleaguemembers; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_communityleaguemembers (id, created_at, updated_at, league_id, team_id) FROM stdin;
\.


--
-- Data for Name: team_player; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_player (created_at, updated_at, id, name, surname, "position", cost, club_id, card_image, card_image_link, t_short_number) FROM stdin;
2025-04-25 12:40:19.447969+00	2025-04-27 20:40:06.798275+00	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	Иван	Тихомиров	def	4.20	isloch		https://championship.abff.by/uploads/images/players/67fca355bf404054133277.jpg	3
2025-04-22 15:11:53.202633+00	2025-04-27 20:41:03.08233+00	05bcbe76-eb91-44e1-b950-bd7706c90b41	Евгений	Юдчиц	def	5.50	isloch		https://championship.abff.by/uploads/images/players/67fca0183e28e569024528.jpg	99
2025-04-25 12:39:00.982426+00	2025-04-27 20:41:14.196972+00	12bdec39-2820-4963-86cd-c9a8fe27d4a9	Андрей	Климович	gkp	4.00	isloch		https://championship.abff.by/uploads/images/players/67fca27561e1c788595785.jpg	1
2025-04-22 15:11:17.466381+00	2025-04-27 20:42:26.168139+00	3aecd5da-cf32-47fa-bd58-905f424e6a76	Александр	Свирский	gkp	4.40	isloch		https://championship.abff.by/uploads/images/players/67fca8f546329802309620.jpg	28
2025-04-25 12:39:53.145265+00	2025-04-27 20:42:38.229832+00	fd40d348-2787-4eff-af43-13cfc072a01f	Кирилл	Родионов	def	4.50	isloch		https://championship.abff.by/uploads/images/players/67fca875b7d6e521386327.jpg	17
2025-04-22 15:10:14.776218+00	2025-04-27 20:43:00.117543+00	ac9bb7eb-9688-487d-9585-bef5bfbda800	Руслан	Хадаркевич	def	5.10	minsk		https://championship.abff.by/uploads/images/players/67f7d4d093606047992415.jpg	3
2025-04-22 15:09:28.112048+00	2025-04-27 20:43:50.144343+00	60b00664-ce7c-42e4-a801-329197f539d4	Александр	Гутор	gkp	4.20	minsk		https://championship.abff.by/uploads/images/players/67f7d5eb8c07c419459140.jpg	30
2025-05-04 15:17:06.347181+00	2025-05-04 15:17:06.347202+00	eb644324-2ff4-4295-bbd2-c9ba1a0be15d	Артем	Сороко	gkp	4.20	arsenal		https://championship.abff.by/uploads/images/players/67f8ba8c692e1177519956.jpg	30
2025-05-04 15:17:43.469439+00	2025-05-04 15:17:43.469462+00	19a79a7b-f143-4572-b1c8-047a3b0bf281	Иван	Санько	gkp	4.00	arsenal		https://championship.abff.by/uploads/images/players/67f8bb4966260289761969.jpg	1
2025-05-04 15:18:46.26777+00	2025-05-04 15:18:46.267793+00	862ef733-39be-4af4-b669-731f8724ff86	Кирилл	Волков	def	4.70	arsenal		https://championship.abff.by/uploads/images/players/67f8ba8362a78567912728.jpg	99
2025-05-04 15:19:21.434381+00	2025-05-04 15:19:21.434405+00	be063b12-15e1-4d80-87f4-2d6e3d6cff7f	Александр	Михаленко	def	4.80	arsenal		https://championship.abff.by/uploads/images/players/67f8b1da716f0299972305.jpg	18
2025-05-04 15:22:02.917442+00	2025-05-04 15:22:02.917472+00	a53fddff-7078-4232-b794-68dd9d160dff	Глеб	Якушевич	def	4.70	arsenal		https://championship.abff.by/uploads/images/players/67f8b1c8c824f106341586.jpg	81
2025-05-04 15:23:44.682473+00	2025-05-04 15:23:44.682501+00	f24e9b1b-529a-44d8-9529-7b000f304736	Михаил	Козакевич	gkp	4.70	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd0277d840e472541056.jpg	16
2025-05-04 15:24:18.029577+00	2025-05-04 15:24:18.029598+00	33fa37b6-0ab1-458d-aa2b-5e47bb50ab0d	Дмитрий	Дударь	gkp	4.10	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd00d2d789f885770247.jpg	91
2025-05-04 15:24:54.425457+00	2025-05-04 15:24:54.425478+00	917bd825-69bb-4bb0-80cc-d5d4425f66c6	Артем	Рахманов	def	4.90	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd0181a4870335207893.jpg	33
2025-05-04 15:27:27.115769+00	2025-05-04 15:27:27.115789+00	e2d31898-257d-4c2b-991d-6537aa1a21fd	Максим	Касараб	def	4.90	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd00cbaa69c008026573.jpg	15
2025-05-04 17:48:11.414855+00	2025-05-04 17:48:11.414877+00	8c7a92a3-d7f7-4569-b258-dc248416a8d5	Артем	Турич	mid	4.40	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd00dcf3d7d149149739.jpg	27
2025-05-04 17:52:01.135792+00	2025-05-04 17:52:01.135822+00	96d94865-df4f-465c-9cdd-09b44db06783	Михаил	Гордейчук	mid	7.60	dinamo-brest		https://championship.abff.by/uploads/images/players/67fd02722af67745089733.jpg	62
2025-05-04 17:57:54.007353+00	2025-05-04 17:57:54.007376+00	4c46f54c-3c4b-4266-af78-d61eebaf14b2	Евгений	Малашевич	mid	7.10	dinamo-minsk		https://championship.abff.by/uploads/images/players/67fd0b3c48b2d918842148.jpg	7
2025-05-04 17:58:30.312751+00	2025-05-04 17:58:30.312771+00	7e5f9082-60f3-476e-afb6-3dad1b69add3	Евгений	Шевченко	mid	6.80	dinamo-minsk		https://championship.abff.by/uploads/images/players/67d1891b648ae610359874.jpg	21
2025-05-04 18:00:20.45902+00	2025-05-04 18:00:39.02006+00	0f27853b-3306-4f9b-9bf7-6c644529e5a2	Иван	Бахар	fwd	7.90	dinamo-minsk		https://championship.abff.by/uploads/images/players/67d189a3e3780287287865.jpg	17
2025-05-04 18:01:28.347349+00	2025-05-04 18:01:28.347369+00	4d685dbb-d391-433a-9703-5b9350e0c059	Денис	Козловский	fwd	8.30	maxline-vitebsk		https://championship.abff.by/uploads/images/players/67da8662c0996816348780.jpg	7
2025-05-04 18:05:08.855182+00	2025-05-04 18:05:08.855203+00	48c9f281-857a-4324-95ec-32c174395601	Денис	Овсянников	fwd	6.50	maxline-vitebsk		https://championship.abff.by/uploads/images/players/67da849fd9b33712380566.jpg	92
2025-05-04 15:28:03.78177+00	2025-05-25 21:24:28.473813+00	007cf653-6d56-4a55-ad03-6e0715d2f864	Артем	Быков	mid	82.50	dinamo-brest		https://championship.abff.by/uploads/images/players/67fcff488aa95436711234.jpg	7
\.


--
-- Data for Name: team_team; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_team (created_at, updated_at, id, name, points, profile_id) FROM stdin;
2025-05-05 20:49:57.315392+00	2025-05-05 20:49:57.31543+00	e23506e5-8da2-4908-a960-8a61858cc800	Команда: user1	0	44b8287d-0fbd-4fd2-9f08-28996effd50c
2025-05-09 22:32:52.083141+00	2025-05-09 22:32:52.083163+00	e39fddb3-04a0-4aaf-80c6-aad1f595bb60	Команда: user2	0	5b458b05-ea82-47de-87a4-566f5d059323
\.


--
-- Data for Name: team_teamplayer; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.team_teamplayer (id, is_captain, is_starter, player_id, team_id) FROM stdin;
6	f	t	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	e23506e5-8da2-4908-a960-8a61858cc800
7	f	t	05bcbe76-eb91-44e1-b950-bd7706c90b41	e23506e5-8da2-4908-a960-8a61858cc800
9	f	t	ac9bb7eb-9688-487d-9585-bef5bfbda800	e23506e5-8da2-4908-a960-8a61858cc800
11	f	t	862ef733-39be-4af4-b669-731f8724ff86	e23506e5-8da2-4908-a960-8a61858cc800
12	f	f	be063b12-15e1-4d80-87f4-2d6e3d6cff7f	e23506e5-8da2-4908-a960-8a61858cc800
13	f	t	007cf653-6d56-4a55-ad03-6e0715d2f864	e23506e5-8da2-4908-a960-8a61858cc800
14	f	t	8c7a92a3-d7f7-4569-b258-dc248416a8d5	e23506e5-8da2-4908-a960-8a61858cc800
15	f	t	96d94865-df4f-465c-9cdd-09b44db06783	e23506e5-8da2-4908-a960-8a61858cc800
16	f	f	4c46f54c-3c4b-4266-af78-d61eebaf14b2	e23506e5-8da2-4908-a960-8a61858cc800
17	f	f	7e5f9082-60f3-476e-afb6-3dad1b69add3	e23506e5-8da2-4908-a960-8a61858cc800
18	t	t	0f27853b-3306-4f9b-9bf7-6c644529e5a2	e23506e5-8da2-4908-a960-8a61858cc800
19	f	t	4d685dbb-d391-433a-9703-5b9350e0c059	e23506e5-8da2-4908-a960-8a61858cc800
20	f	t	48c9f281-857a-4324-95ec-32c174395601	e23506e5-8da2-4908-a960-8a61858cc800
126	f	t	1a084d3b-370d-4bf8-9bf4-0d8a7cc3025e	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
127	f	t	05bcbe76-eb91-44e1-b950-bd7706c90b41	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
128	f	t	12bdec39-2820-4963-86cd-c9a8fe27d4a9	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
129	f	t	ac9bb7eb-9688-487d-9585-bef5bfbda800	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
130	f	f	60b00664-ce7c-42e4-a801-329197f539d4	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
131	f	t	862ef733-39be-4af4-b669-731f8724ff86	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
132	f	f	be063b12-15e1-4d80-87f4-2d6e3d6cff7f	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
133	f	t	007cf653-6d56-4a55-ad03-6e0715d2f864	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
134	f	t	8c7a92a3-d7f7-4569-b258-dc248416a8d5	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
135	f	t	96d94865-df4f-465c-9cdd-09b44db06783	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
136	f	f	4c46f54c-3c4b-4266-af78-d61eebaf14b2	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
137	f	f	7e5f9082-60f3-476e-afb6-3dad1b69add3	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
138	t	t	0f27853b-3306-4f9b-9bf7-6c644529e5a2	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
139	f	t	4d685dbb-d391-433a-9703-5b9350e0c059	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
140	f	t	48c9f281-857a-4324-95ec-32c174395601	e39fddb3-04a0-4aaf-80c6-aad1f595bb60
10	f	t	60b00664-ce7c-42e4-a801-329197f539d4	e23506e5-8da2-4908-a960-8a61858cc800
141	f	f	3aecd5da-cf32-47fa-bd58-905f424e6a76	e23506e5-8da2-4908-a960-8a61858cc800
\.


--
-- Data for Name: user_user; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.user_user (id, password, last_login, is_superuser, created_at, updated_at, username, is_active, is_staff, uuid, deleted_at, md5_password) FROM stdin;
1		\N	f	2025-04-16 13:02:39.20777+00	2025-04-16 13:02:39.207788+00	username	t	f	2bb7db73-8dfa-4039-9474-9b5f0e872fdd	\N	\N
3	pbkdf2_sha256$870000$0JlsImbTT8hUe2owNudzmQ$raKq2SP2/S1fQAnQgqDAt93w7Ig7ET62RVVKRVvikgA=	\N	f	2025-04-16 13:59:58.695743+00	2025-04-16 13:59:59.094077+00	panton8	t	f	717440fb-81a5-452c-adb2-e2ff0773cf35	\N	\N
6	pbkdf2_sha256$870000$ED9pl4OOC4oPrMasAmffRa$kAmA3fxm+bsumftAhChkXf6lYVEcDMzWVxP6GjBMpjs=	\N	f	2025-04-21 08:10:39.483461+00	2025-05-02 11:42:47.569401+00	user1	t	f	7434815c-ee26-4a17-8c83-c726ee53ff2f	\N	\N
7	pbkdf2_sha256$870000$LHfGM4PFFhvWyHQ1kkuJl9$Sy7AUixxm8ftb/TVyCdt29OkzNz23w0tmSAL4Pg8jFY=	\N	f	2025-05-09 22:17:17.73681+00	2025-05-09 22:17:18.093871+00	user2	t	f	2db27853-08e0-4d2f-a53f-78b958081ef8	\N	\N
8	pbkdf2_sha256$870000$jpiiuURFGErk5Uhb8LkSvg$Z1kcKfR1rJa9/0fljL5UrBA7t4TyisEUaUHWA6Y69NA=	\N	f	2025-05-09 22:49:56.986258+00	2025-05-09 22:49:57.463766+00	user3	t	f	a165ea57-ae57-4538-9bb5-70d68c384e13	\N	\N
2	pbkdf2_sha256$870000$BNR5lHGRziCJQJxpU8WgJo$k5Wyva/2stoWDbdNZsqZ1YVLFrvTblktuaY0g30ITZs=	2025-06-13 10:08:30.766066+00	t	2025-04-16 13:05:55.613654+00	2025-04-16 13:06:48.015629+00	admin	t	t	4689dd62-7f9a-46b8-bfbb-eb4cac4d03dd	\N	\N
\.


--
-- Data for Name: user_user_groups; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.user_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: user_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.user_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: user_userprofile; Type: TABLE DATA; Schema: public; Owner: fantasy_league
--

COPY public.user_userprofile (created_at, updated_at, id, email, budget, user_id) FROM stdin;
2025-04-16 13:59:59.095806+00	2025-04-16 13:59:59.095822+00	908fcf00-c452-4130-9223-7519bbdc7678		100.00	3
2025-05-09 22:49:57.465881+00	2025-05-09 22:49:57.4659+00	32c02a99-bc55-4c0b-a3ff-1f4ee8071a7d	\N	100.00	8
2025-05-09 22:17:18.099568+00	2025-05-10 21:51:40.887591+00	5b458b05-ea82-47de-87a4-566f5d059323	\N	17.20	7
2025-04-21 08:10:39.842838+00	2025-05-24 12:36:39.527728+00	44b8287d-0fbd-4fd2-9f08-28996effd50c	\N	1.30	6
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 89, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 73, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 22, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: team_clubinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.team_clubinfo_id_seq', 2, true);


--
-- Name: team_communityleaguemembers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.team_communityleaguemembers_id_seq', 1, false);


--
-- Name: team_teamplayer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.team_teamplayer_id_seq', 141, true);


--
-- Name: user_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.user_user_groups_id_seq', 1, false);


--
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.user_user_id_seq', 8, true);


--
-- Name: user_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy_league
--

SELECT pg_catalog.setval('public.user_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: match_gameweek match_gameweek_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_gameweek
    ADD CONSTRAINT match_gameweek_pkey PRIMARY KEY (id);


--
-- Name: match_lineup match_lineup_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_lineup
    ADD CONSTRAINT match_lineup_pkey PRIMARY KEY (id);


--
-- Name: match_match match_match_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_match
    ADD CONSTRAINT match_match_pkey PRIMARY KEY (id);


--
-- Name: match_matchaction match_matchaction_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_matchaction
    ADD CONSTRAINT match_matchaction_pkey PRIMARY KEY (code);


--
-- Name: match_matchevent match_matchevent_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_matchevent
    ADD CONSTRAINT match_matchevent_pkey PRIMARY KEY (id);


--
-- Name: match_news match_news_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_news
    ADD CONSTRAINT match_news_pkey PRIMARY KEY (id);


--
-- Name: match_lineup match_unique_player; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_lineup
    ADD CONSTRAINT match_unique_player UNIQUE (match_id, player_id);


--
-- Name: statistics_gameweekstats statistics_gameweekstats_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.statistics_gameweekstats
    ADD CONSTRAINT statistics_gameweekstats_pkey PRIMARY KEY (id);


--
-- Name: team_club team_club_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_club
    ADD CONSTRAINT team_club_pkey PRIMARY KEY (code_name);


--
-- Name: team_clubinfo team_clubinfo_club_id_26dc76ca_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_clubinfo
    ADD CONSTRAINT team_clubinfo_club_id_26dc76ca_uniq UNIQUE (club_id);


--
-- Name: team_clubinfo team_clubinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_clubinfo
    ADD CONSTRAINT team_clubinfo_pkey PRIMARY KEY (id);


--
-- Name: team_communityleague team_communityleague_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_communityleague
    ADD CONSTRAINT team_communityleague_pkey PRIMARY KEY (code_name);


--
-- Name: team_communityleaguemembers team_communityleaguemembers_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_communityleaguemembers
    ADD CONSTRAINT team_communityleaguemembers_pkey PRIMARY KEY (id);


--
-- Name: team_player team_player_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT team_player_pkey PRIMARY KEY (id);


--
-- Name: team_teamplayer team_player_unique; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_teamplayer
    ADD CONSTRAINT team_player_unique UNIQUE (team_id, player_id);


--
-- Name: team_team team_team_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_team
    ADD CONSTRAINT team_team_pkey PRIMARY KEY (id);


--
-- Name: team_team team_team_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_team
    ADD CONSTRAINT team_team_profile_id_key UNIQUE (profile_id);


--
-- Name: team_teamplayer team_teamplayer_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_teamplayer
    ADD CONSTRAINT team_teamplayer_pkey PRIMARY KEY (id);


--
-- Name: user_user_groups user_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_pkey PRIMARY KEY (id);


--
-- Name: user_user_groups user_user_groups_user_id_group_id_bb60391f_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_group_id_bb60391f_uniq UNIQUE (user_id, group_id);


--
-- Name: user_user user_user_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_pkey PRIMARY KEY (id);


--
-- Name: user_user_user_permissions user_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: user_user_user_permissions user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_permission_id_64f4d5b8_uniq UNIQUE (user_id, permission_id);


--
-- Name: user_user user_user_username_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_username_key UNIQUE (username);


--
-- Name: user_user user_user_uuid_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user
    ADD CONSTRAINT user_user_uuid_key UNIQUE (uuid);


--
-- Name: user_userprofile user_userprofile_email_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_userprofile
    ADD CONSTRAINT user_userprofile_email_key UNIQUE (email);


--
-- Name: user_userprofile user_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_userprofile
    ADD CONSTRAINT user_userprofile_pkey PRIMARY KEY (id);


--
-- Name: user_userprofile user_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_userprofile
    ADD CONSTRAINT user_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: match_lineup_match_id_a4ec95da; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_lineup_match_id_a4ec95da ON public.match_lineup USING btree (match_id);


--
-- Name: match_lineup_player_id_e1ac99ec; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_lineup_player_id_e1ac99ec ON public.match_lineup USING btree (player_id);


--
-- Name: match_match_away_club_id_eaed7dc8; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_match_away_club_id_eaed7dc8 ON public.match_match USING btree (away_club_id);


--
-- Name: match_match_away_club_id_eaed7dc8_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_match_away_club_id_eaed7dc8_like ON public.match_match USING btree (away_club_id varchar_pattern_ops);


--
-- Name: match_match_gameweek_id_ae5404f1; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_match_gameweek_id_ae5404f1 ON public.match_match USING btree (gameweek_id);


--
-- Name: match_match_home_club_id_cdc69e06; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_match_home_club_id_cdc69e06 ON public.match_match USING btree (home_club_id);


--
-- Name: match_match_home_club_id_cdc69e06_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_match_home_club_id_cdc69e06_like ON public.match_match USING btree (home_club_id varchar_pattern_ops);


--
-- Name: match_matchaction_code_58b47927_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_matchaction_code_58b47927_like ON public.match_matchaction USING btree (code varchar_pattern_ops);


--
-- Name: match_matchevent_action_id_86290c27; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_matchevent_action_id_86290c27 ON public.match_matchevent USING btree (action_id);


--
-- Name: match_matchevent_action_id_86290c27_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_matchevent_action_id_86290c27_like ON public.match_matchevent USING btree (action_id varchar_pattern_ops);


--
-- Name: match_matchevent_match_id_fa7acf27; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_matchevent_match_id_fa7acf27 ON public.match_matchevent USING btree (match_id);


--
-- Name: match_matchevent_player_id_a6fdb30c; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX match_matchevent_player_id_a6fdb30c ON public.match_matchevent USING btree (player_id);


--
-- Name: statistics_gameweekstats_gameweek_id_11832aeb; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX statistics_gameweekstats_gameweek_id_11832aeb ON public.statistics_gameweekstats USING btree (gameweek_id);


--
-- Name: statistics_gameweekstats_player_id_72886d61; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX statistics_gameweekstats_player_id_72886d61 ON public.statistics_gameweekstats USING btree (player_id);


--
-- Name: team_club_code_name_43c5ee63_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_club_code_name_43c5ee63_like ON public.team_club USING btree (code_name varchar_pattern_ops);


--
-- Name: team_clubinfo_club_id_26dc76ca_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_clubinfo_club_id_26dc76ca_like ON public.team_clubinfo USING btree (club_id varchar_pattern_ops);


--
-- Name: team_communityleague_code_name_422ba574_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_communityleague_code_name_422ba574_like ON public.team_communityleague USING btree (code_name varchar_pattern_ops);


--
-- Name: team_communityleaguemembers_league_id_84ce4558; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_communityleaguemembers_league_id_84ce4558 ON public.team_communityleaguemembers USING btree (league_id);


--
-- Name: team_communityleaguemembers_league_id_84ce4558_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_communityleaguemembers_league_id_84ce4558_like ON public.team_communityleaguemembers USING btree (league_id varchar_pattern_ops);


--
-- Name: team_communityleaguemembers_team_id_f696ccd0; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_communityleaguemembers_team_id_f696ccd0 ON public.team_communityleaguemembers USING btree (team_id);


--
-- Name: team_player_club_id_a5a249b6; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_player_club_id_a5a249b6 ON public.team_player USING btree (club_id);


--
-- Name: team_player_club_id_a5a249b6_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_player_club_id_a5a249b6_like ON public.team_player USING btree (club_id varchar_pattern_ops);


--
-- Name: team_teamplayer_player_id_ce0badb2; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_teamplayer_player_id_ce0badb2 ON public.team_teamplayer USING btree (player_id);


--
-- Name: team_teamplayer_team_id_a2885497; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX team_teamplayer_team_id_a2885497 ON public.team_teamplayer USING btree (team_id);


--
-- Name: user_user_groups_group_id_c57f13c0; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_user_groups_group_id_c57f13c0 ON public.user_user_groups USING btree (group_id);


--
-- Name: user_user_groups_user_id_13f9a20d; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_user_groups_user_id_13f9a20d ON public.user_user_groups USING btree (user_id);


--
-- Name: user_user_user_permissions_permission_id_ce49d4de; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_user_user_permissions_permission_id_ce49d4de ON public.user_user_user_permissions USING btree (permission_id);


--
-- Name: user_user_user_permissions_user_id_31782f58; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_user_user_permissions_user_id_31782f58 ON public.user_user_user_permissions USING btree (user_id);


--
-- Name: user_user_username_e2bdfe0c_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_user_username_e2bdfe0c_like ON public.user_user USING btree (username varchar_pattern_ops);


--
-- Name: user_userprofile_email_85a01d3f_like; Type: INDEX; Schema: public; Owner: fantasy_league
--

CREATE INDEX user_userprofile_email_85a01d3f_like ON public.user_userprofile USING btree (email varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_lineup match_lineup_match_id_a4ec95da_fk_match_match_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_lineup
    ADD CONSTRAINT match_lineup_match_id_a4ec95da_fk_match_match_id FOREIGN KEY (match_id) REFERENCES public.match_match(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_lineup match_lineup_player_id_e1ac99ec_fk_team_player_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_lineup
    ADD CONSTRAINT match_lineup_player_id_e1ac99ec_fk_team_player_id FOREIGN KEY (player_id) REFERENCES public.team_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_match match_match_away_club_id_eaed7dc8_fk_team_club_code_name; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_match
    ADD CONSTRAINT match_match_away_club_id_eaed7dc8_fk_team_club_code_name FOREIGN KEY (away_club_id) REFERENCES public.team_club(code_name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_match match_match_gameweek_id_ae5404f1_fk_match_gameweek_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_match
    ADD CONSTRAINT match_match_gameweek_id_ae5404f1_fk_match_gameweek_id FOREIGN KEY (gameweek_id) REFERENCES public.match_gameweek(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_match match_match_home_club_id_cdc69e06_fk_team_club_code_name; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_match
    ADD CONSTRAINT match_match_home_club_id_cdc69e06_fk_team_club_code_name FOREIGN KEY (home_club_id) REFERENCES public.team_club(code_name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_matchevent match_matchevent_action_id_86290c27_fk_match_matchaction_code; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_matchevent
    ADD CONSTRAINT match_matchevent_action_id_86290c27_fk_match_matchaction_code FOREIGN KEY (action_id) REFERENCES public.match_matchaction(code) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_matchevent match_matchevent_match_id_fa7acf27_fk_match_match_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_matchevent
    ADD CONSTRAINT match_matchevent_match_id_fa7acf27_fk_match_match_id FOREIGN KEY (match_id) REFERENCES public.match_match(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: match_matchevent match_matchevent_player_id_a6fdb30c_fk_team_player_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.match_matchevent
    ADD CONSTRAINT match_matchevent_player_id_a6fdb30c_fk_team_player_id FOREIGN KEY (player_id) REFERENCES public.team_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: statistics_gameweekstats statistics_gameweeks_gameweek_id_11832aeb_fk_match_gam; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.statistics_gameweekstats
    ADD CONSTRAINT statistics_gameweeks_gameweek_id_11832aeb_fk_match_gam FOREIGN KEY (gameweek_id) REFERENCES public.match_gameweek(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: statistics_gameweekstats statistics_gameweekstats_player_id_72886d61_fk_team_player_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.statistics_gameweekstats
    ADD CONSTRAINT statistics_gameweekstats_player_id_72886d61_fk_team_player_id FOREIGN KEY (player_id) REFERENCES public.team_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_clubinfo team_clubinfo_club_id_26dc76ca_fk_team_club_code_name; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_clubinfo
    ADD CONSTRAINT team_clubinfo_club_id_26dc76ca_fk_team_club_code_name FOREIGN KEY (club_id) REFERENCES public.team_club(code_name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_communityleaguemembers team_communityleague_league_id_84ce4558_fk_team_comm; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_communityleaguemembers
    ADD CONSTRAINT team_communityleague_league_id_84ce4558_fk_team_comm FOREIGN KEY (league_id) REFERENCES public.team_communityleague(code_name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_communityleaguemembers team_communityleaguemembers_team_id_f696ccd0_fk_team_team_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_communityleaguemembers
    ADD CONSTRAINT team_communityleaguemembers_team_id_f696ccd0_fk_team_team_id FOREIGN KEY (team_id) REFERENCES public.team_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_player team_player_club_id_a5a249b6_fk_team_club_code_name; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_player
    ADD CONSTRAINT team_player_club_id_a5a249b6_fk_team_club_code_name FOREIGN KEY (club_id) REFERENCES public.team_club(code_name) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_team team_team_profile_id_aa81bfef_fk_user_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_team
    ADD CONSTRAINT team_team_profile_id_aa81bfef_fk_user_userprofile_id FOREIGN KEY (profile_id) REFERENCES public.user_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_teamplayer team_teamplayer_player_id_ce0badb2_fk_team_player_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_teamplayer
    ADD CONSTRAINT team_teamplayer_player_id_ce0badb2_fk_team_player_id FOREIGN KEY (player_id) REFERENCES public.team_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: team_teamplayer team_teamplayer_team_id_a2885497_fk_team_team_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.team_teamplayer
    ADD CONSTRAINT team_teamplayer_team_id_a2885497_fk_team_team_id FOREIGN KEY (team_id) REFERENCES public.team_team(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_groups user_user_groups_group_id_c57f13c0_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_group_id_c57f13c0_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_groups user_user_groups_user_id_13f9a20d_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_groups
    ADD CONSTRAINT user_user_groups_user_id_13f9a20d_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_user_permissions user_user_user_permi_permission_id_ce49d4de_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permi_permission_id_ce49d4de_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_user_user_permissions user_user_user_permissions_user_id_31782f58_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_user_user_permissions
    ADD CONSTRAINT user_user_user_permissions_user_id_31782f58_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_userprofile user_userprofile_user_id_2474538d_fk_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy_league
--

ALTER TABLE ONLY public.user_userprofile
    ADD CONSTRAINT user_userprofile_user_id_2474538d_fk_user_user_id FOREIGN KEY (user_id) REFERENCES public.user_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

