# Generated by Django 5.1.7 on 2025-04-22 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('team', '0004_alter_clubinfo_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWeekStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('saves', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('own_goals', models.PositiveSmallIntegerField(default=0)),
                ('penalties_saved', models.PositiveSmallIntegerField(default=0)),
                ('penalties_missed', models.PositiveSmallIntegerField(default=0)),
                ('goals_conceded', models.PositiveSmallIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.gameweek')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
