# Generated by Django 5.1.7 on 2025-04-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('foundation_date', models.DateField()),
                ('stadium', models.CharField(max_length=255)),
                ('stadium_capacity', models.PositiveIntegerField(default=1000)),
                ('info', models.TextField()),
                ('site_link', models.URLField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.club')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
