# Generated by Django 5.1.7 on 2025-04-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_clubinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_info', to='team.club'),
        ),
    ]
