# Generated by Django 5.1.7 on 2025-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_clubinfo_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='card_image',
            field=models.FileField(blank=True, null=True, upload_to='players/'),
        ),
        migrations.AddField(
            model_name='player',
            name='card_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='t_short_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
