# Generated by Django 5.1.7 on 2025-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='additional_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
