# Generated by Django 5.1.7 on 2025-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_matchevent_additional_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='processed',
        ),
    ]
