# Generated by Django 5.1.7 on 2025-04-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_remove_match_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('for_display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='for_display',
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='match.matchaction'),
        ),
    ]
