# Generated by Django 5.1.7 on 2025-05-25 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_matchaction_remove_matchevent_for_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('photo', models.URLField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
    ]
