# Generated by Django 5.1.7 on 2025-06-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
